In [1]:
!pip install numpy pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/text.csv")

In [4]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
df.head()

text  label
0      i just feel really helpless and heavy hearted      4
1  ive enjoyed being able to slouch about relax a...      0
2  i gave up my internship with the dmrg and am f...      4
3                         i dont know i feel so lost      0
4  i am a kindergarten teacher and i am thoroughl...      4

In [6]:
labels_def = {
    "0":"Sad",
    "1":"Happy",
    "2":"Love",
    "3":"Angry",
    "4":"Scared",
    "5":"Surpised"
}

In [7]:
!pip uninstall tensorflow | y
!pip install tensorflow[and-cuda]==2.15
!pip install "tensorflow-text==2.15.*"
!pip install -U "tf-models-official==2.15.*"
!pip install scikit-learn
!pip install "tensorflow-hub"

/usr/bin/sh: 1: y: not found
ERROR: Pipe to stdout was broken
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
  Using cached tensorflow-2.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached ml_dtypes-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
  Using cached nvidia_cublas_cu12-12.2.5.6-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.2.142-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cuda_nvcc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_nvrtc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cudnn_cu12-8.9.4.25-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cufft_c

In [8]:
import tensorflow as tf
print(tf.config.list_physical_devices())
import tensorflow_text as text
import tensorflow_hub as hub

tf.config.run_functions_eagerly(True)


from sklearn.model_selection import train_test_split

2024-03-31 22:03:30.168681: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-31 22:03:30.197023: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-31 22:03:30.197044: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-31 22:03:30.197702: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-31 22:03:30.202002: I tensorflow/core/platform/cpu_feature_guar

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [9]:
tf.config.experimental.get_memory_info('GPU:0')


2024-03-31 22:03:31.762318: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-03-31 22:03:31.762508: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-03-31 22:03:31.762593: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

{'current': 0, 'peak': 0}

In [10]:
num_classes = len(labels_def)
num_classes

6

In [11]:
X = df['text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train, num_classes)
y_test_encoded = tf.keras.utils.to_categorical(y_test, num_classes)

## Tfidf Preprocessor

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
vectorizer = TfidfVectorizer()

In [14]:
X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

In [15]:
# X_train_final = X_train.toarray()
# X_test_final = X_test.toarray()

In [16]:
# X_train_final

In [17]:
# input_shape = X_train_final.shape
# input_shape

In [18]:
# # Input Layer
# input_layer = tf.keras.Input(shape=input_shape)

# # Hidden Layers
# dense1 = tf.keras.layers.Dense(250, activation='relu')(input_layer)
# dropout1 = tf.keras.layers.Dropout(0.2)(dense1)
# dense2 = tf.keras.layers.Dense(125, activation='relu')(dropout1)
# dropout2 = tf.keras.layers.Dropout(0.1)(dense2)

# # Output layer
# output = tf.keras.layers.Dense(num_classes, activation='softmax', name='output')(dropout2)

# tfidf_model = tf.keras.Model(inputs=input_layer, outputs=output)

# tfidf_model.compile()

In [19]:
# tfidf_model.fit(X_train, y_train, epochs=10)

## BERT Preprocessor From Tensorflow

In [20]:
max_length = 0
def find_max_length(text):
    global max_length
    if len(text) > max_length:
        max_length = len(text)

In [21]:
# X_train.apply(find_max_length)

In [22]:
max_length

0

In [23]:
#### Uncased 
# preprocess_url = 'https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-uncased-preprocess/versions/3'
# encoder_url = 'https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/bert-en-uncased-l-12-h-768-a-12/versions/2'

#### Cased 
preprocess_url = "https://kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-cased-preprocess/versions/3"
encoder_url = "https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-cased-l-12-h-768-a-12/versions/4"

In [24]:
test_text = ['Great movie. I wish it was worse', 'I love programming in python']

In [25]:
preprocessor_model = hub.KerasLayer(preprocess_url)

In [26]:
text_preprocessed = preprocessor_model(test_text)
text_preprocessed

{'input_mask': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 'input_type_ids': <tf.Tensor: shape

In [27]:
# bert_encoder_model = hub.KerasLayer(encoder_url)
# bert_results = bert_encoder_model(text_preprocessed)
# bert_results.keys()

In [28]:
# bert_results['pooled_output']

In [29]:
# bert_results['encoder_outputs']

In [30]:
# !pip install --upgrade tensorflow-hub
# !pip install --upgrade tensorflow

In [31]:
!pip install keras_nlp
import keras_nlp

Using TensorFlow backend


In [32]:
classifer = keras_nlp.models.BertClassifier.from_preset(
    'bert_base_en_uncased',
    num_classes=num_classes,
    activation='softmax',
)

100%|████████████████████████████████████████████████████████████████████| 510/510 [00:00<00:00, 509kB/s]
100%|█████████████████████████████████████████████████████████████████| 418M/418M [00:16<00:00, 26.5MB/s]
/usr/local/lib/python3.11/dist-packages/keras_nlp/src/models/backbone.py:46: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  return id(getattr(self, attr)) not in self._functional_layer_ids
/usr/local/lib/python3.11/dist-packages/keras_nlp/src/models/backbone.py:46: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  return id(getattr(self, attr)) not in self._functional_layer_ids
100%|████████████████████████████████████████████████████████████████████| 547/547 [00:00<00:00, 525kB/s]
100%|█████████████████████████████████████████████████████████████████| 

In [37]:
classifer.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [44]:
import os
os.environ['TF_GPU_ALLOCATOR'] = 'cuda_malloc_async'

In [39]:
# tf.keras.backend.clear_session()

In [41]:
tf.__version__

'2.15.1'

In [42]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [46]:
classifer.fit(X_train, y_train, epochs=1, batch_size=512)

2024-03-31 22:08:20.311148: W external/local_tsl/tsl/framework/bfc_allocator.cc:485] Allocator (GPU_0_bfc) ran out of memory trying to allocate 768.00MiB (rounded to 805306368)requested by op ResourceGather
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2024-03-31 22:08:20.311175: I external/local_tsl/tsl/framework/bfc_allocator.cc:1039] BFCAllocator dump for GPU_0_bfc
2024-03-31 22:08:20.311182: I external/local_tsl/tsl/framework/bfc_allocator.cc:1046] Bin (256): 	Total Chunks: 25, Chunks in use: 24. 6.2KiB allocated for chunks. 6.0KiB in use in bin. 145B client-requested in use in bin.
2024-03-31 22:08:20.311185: I external/local_tsl/tsl/framework/bfc_allocator.cc:1046] Bin (512): 	Total Chunks: 1, Chunks in use: 0. 512B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-03-31 22:08:20.311189: I ext

ResourceExhaustedError: Exception encountered when calling layer 'token_embedding' (type ReversibleEmbedding).

{{function_node __wrapped__ResourceGather_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[512,512,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:ResourceGather] name: 

Call arguments received by layer 'token_embedding' (type ReversibleEmbedding):
  • inputs=tf.Tensor(shape=(512, 512), dtype=int32)
  • reverse=False

In [49]:
# Bert Layers
text_input = tf.keras.Input(shape=(), dtype=tf.string, name='text')
bert_preprocess = hub.KerasLayer(preprocess_url, name='preprocessing')
preprocessed_text = bert_preprocess(text_input)
bert_encoder = hub.KerasLayer(encoder_url, 
                              trainable=True, 
                              name='BERT_encoder')
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1)(outputs['pooled_output'])
l = tf.keras.layers.Dense(num_classes, activation='softmax', name='output')(l)

# Construct final model
classifier_model = tf.keras.Model(inputs=[text_input], outputs=[l])

In [50]:
bert_raw_result = classifier_model(tf.constant(test_text))

In [51]:
bert_raw_result

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0.5945428 , 0.05604997, 0.11475545, 0.05196897, 0.15984982,
        0.02283304],
       [0.5795439 , 0.06040187, 0.11725851, 0.06535823, 0.14790559,
        0.02953188]], dtype=float32)>

In [52]:
tf.keras.utils.plot_model(classifier_model)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [53]:
classifier_model.compile(optimizer=tf.keras.optimizers.AdamW(), metrics=['accuracy'], loss=tf.keras.losses.CategoricalCrossentropy())

In [54]:
classifier_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text (InputLayer)           [(None,)]                    0         []                            
                                                                                                  
 preprocessing (KerasLayer)  {'input_mask': (None, 128)   0         ['text[0][0]']                
                             , 'input_type_ids': (None,                                           
                              128),                                                               
                              'input_word_ids': (None,                                            
                             128)}                                                                
                                                                                            

In [55]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [56]:
tf.sysconfig.get_build_info()

OrderedDict([('cpu_compiler', '/usr/lib/llvm-17/bin/clang'),
             ('cuda_compute_capabilities',
              ['sm_50', 'sm_60', 'sm_70', 'sm_75', 'compute_80']),
             ('cuda_version', '12.2'),
             ('cudnn_version', '8'),
             ('is_cuda_build', True),
             ('is_rocm_build', False),
             ('is_tensorrt_build', True)])

In [58]:
classifier_model.fit(X_train, y_train_encoded, epochs=10, batch_size=64)

Epoch 1/10


2024-03-31 22:13:58.052870: W external/local_tsl/tsl/framework/bfc_allocator.cc:485] Allocator (GPU_0_bfc) ran out of memory trying to allocate 96.00MiB (rounded to 100663296)requested by op StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_4/intermediate/einsum/Einsum
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2024-03-31 22:13:58.052970: I external/local_tsl/tsl/framework/bfc_allocator.cc:1039] BFCAllocator dump for GPU_0_bfc
2024-03-31 22:13:58.052996: I external/local_tsl/tsl/framework/bfc_allocator.cc:1046] Bin (256): 	Total Chunks: 79, Chunks in use: 79. 19.8KiB allocated for chunks. 19.8KiB in use in bin. 551B client-requested in use in bin.
2024-03-31 22:13:58.053014: I external/local_tsl/tsl/framework/bfc_allocator.cc:1046] Bin (512): 	Total Chunks: 0, Chunks in use

ResourceExhaustedError: Exception encountered when calling layer 'BERT_encoder' (type KerasLayer).

Graph execution error:

Detected at node transformer/layer_4/intermediate/einsum/Einsum defined at (most recent call last):
<stack traces unavailable>
OOM when allocating tensor with shape[8192,3072] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node transformer/layer_4/intermediate/einsum/Einsum}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__forward_restored_function_body_140718]

Call arguments received by layer 'BERT_encoder' (type KerasLayer):
  • inputs={'input_mask': 'tf.Tensor(shape=(64, 128), dtype=int32)', 'input_type_ids': 'tf.Tensor(shape=(64, 128), dtype=int32)', 'input_word_ids': 'tf.Tensor(shape=(64, 128), dtype=int32)'}
  • training=True

## HuggingFace Transformers Bert

In [71]:
# tf.config.list_physical_devices()

In [70]:
# !pip install transformers

In [69]:
# from transformers import TFBertTokenizer, TFBertModel

In [68]:
# tokenizer = TFBertTokenizer.from_pretrained('bert-base-uncased')
# bert_model = TFBertModel.from_pretrained('bert-base-uncased')

In [67]:
# bert_model(tokenizer(test_text))[1]

In [66]:
# # Input Layer 
# text_input = tf.keras.Input(shape=(), dtype=tf.string)

# # Tokenize Text
# tokenized = tokenizer(text_input)['input_ids']

# # Pass into BERT Model
# bert_outputs = bert_model(tokenized)[0]

# # Processing layers
# dense1 = tf.keras.layers.Dense(128, activation='relu')(bert_outputs)
# dropout1 = tf.keras.layers.Dropout(0.2)(dense1)

# # Output
# output_layer = tf.keras.layers.Dense(num_classes, activation='softmax')

# model = tf.keras.Model(inputs=text_input, outputs=output_layer)

# model.compile()